# Generated by Django 6.0.4 on 2026-05-08 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_code', models.CharField(max_length=20, unique=True)),
                ('bagging_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('dispatched', 'Dispatched')], default='open', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scanned', 'Scanned'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('deposited', 'Deposited')], default='scanned', max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.speedpostbooking')),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='delivery.bag')),
                ('delivery_boy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
