# Generated by Django 6.0.4 on 2026-04-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedPostBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=50, unique=True)),
                ('weight_grams', models.PositiveIntegerField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
